# Este é o NGINX que recebe as requisições da internet
# Ele encaminha para os containers internos

events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=10s;

    # ROTEAMENTO: Redireciona para os projetos
    server {
        listen 80;
        server_name projeto1.empresa;
        location / {
            set $upstream projeto1;
            proxy_pass http://$upstream:80;  # Encaminha para o container 'projeto1'
        }
    }

    server {
        listen 80;
        server_name projeto2.empresa;
        location / {
            set $upstream projeto2;
            proxy_pass http://$upstream:80;  # Encaminha para o container 'projeto2'
        }
    }

        server {
        listen 80;
        server_name projeto3.empresa;
        location / {
            set $upstream projeto3;
            proxy_pass http://$upstream:80;  # Encaminha para o container 'projeto2'
        }
    }
}